name: Build PJ Project
on:
  push:
    branches: [ main ]

jobs:
  build-ubuntu-default:
  # checking pure lib source distribution with plain configure & make
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unzip PJ Project
      run: unzip ./pjproject-2.14.zip
    - name: configure & make
      working-directory: ./pjproject-2.14
      run: ./configure && make 
    - name: Show Build Artifacts
      working-directory: ./pjproject-2.14
      run: ls -l
    - name: Prepare PJSIP bundle
      run: |
        mkdir -p ./pjsip-bundle/lib
        mkdir -p ./pjsip-bundle/include
        # Copy all static and shared libraries and headers from pjlib, pjsip, pjnath, pjmedia
        cp ./pjproject-2.14/pjlib/lib/*.a ./pjsip-bundle/lib/ 2>/dev/null || true
        cp ./pjproject-2.14/pjlib/lib/*.so ./pjsip-bundle/lib/ 2>/dev/null || true
        cp -r ./pjproject-2.14/pjlib/include/* ./pjsip-bundle/include/ 2>/dev/null || true
        cp ./pjproject-2.14/pjsip/lib/*.a ./pjsip-bundle/lib/ 2>/dev/null || true
        cp ./pjproject-2.14/pjsip/lib/*.so ./pjsip-bundle/lib/ 2>/dev/null || true
        cp -r ./pjproject-2.14/pjsip/include/* ./pjsip-bundle/include/ 2>/dev/null || true
        cp ./pjproject-2.14/pjnath/lib/*.a ./pjsip-bundle/lib/ 2>/dev/null || true
        cp ./pjproject-2.14/pjnath/lib/*.so ./pjsip-bundle/lib/ 2>/dev/null || true
        cp -r ./pjproject-2.14/pjnath/include/* ./pjsip-bundle/include/ 2>/dev/null || true
        cp ./pjproject-2.14/pjmedia/lib/*.a ./pjsip-bundle/lib/ 2>/dev/null || true
        cp ./pjproject-2.14/pjmedia/lib/*.so ./pjsip-bundle/lib/ 2>/dev/null || true
        cp -r ./pjproject-2.14/pjmedia/include/* ./pjsip-bundle/include/ 2>/dev/null || true
        # Optionally copy CLI binary for testing
        cp ./pjproject-2.14/pjsip-apps/bin/pjsua-* ./pjsip-bundle/ 2>/dev/null || true
        # Optionally copy third-party libs (example: opus, ssl)
        # cp /usr/lib/x86_64-linux-gnu/libopus.so* ./pjsip-bundle/lib/ 2>/dev/null || true
        # cp /usr/lib/x86_64-linux-gnu/libssl.so* ./pjsip-bundle/lib/ 2>/dev/null || true
        # cp /usr/lib/x86_64-linux-gnu/libcrypto.so* ./pjsip-bundle/lib/ 2>/dev/null || true

    - name: Read VERSION
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION

    - name: Zip PJSIP bundle
      run: |
        cd ./pjsip-bundle
        zip -r ../pjsip-bundle-{{ steps.version.outputs.content }}.zip .

    - name: Upload ZIP to GitHub Release
      # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: 'v${{ steps.version.outputs.content }}'
        files: ./pjsip-bundle-{{ steps.version.outputs.content }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
