name: Build PJ Project
on:
  push:
    branches: [ main ]

jobs:
  build-ubuntu-default:
  # checking pure lib source distribution with plain configure & make
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unzip PJ Project
      run: unzip .pjproject-2.14.zip
    - name: configure & make
      working-directory: ./deps/pjproject-2.14
      run: ./configure && make 
    - name: Show Build Artifacts
      working-directory: ./deps/pjproject-2.14
      run: ls -l
